version: '3.1'

services:
  db:
    image: postgres:13.1-alpine
    restart: always
    environment: 
      POSTGRES_PASSWORD: todo
    volumes: 
      - ./src/scripts/database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - 5433:5432
    